##############################################################################
#
#     definition.py
#     Copyright (c) 2020 Raphael DINGE
#
#Tab=3########################################################################



{
   'class': 'BoardDaisySeed',
   'pins': {
      'Pin0': {
         'type': 'gpio',
         'physical.location': 1,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(0)',
         'bind.output': 'gpo(0)',
      },
      'Pin1': {
         'type': 'gpio',
         'physical.location': 2,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(1)',
         'bind.output': 'gpo(1)',
      },
      'Pin2': {
         'type': 'gpio',
         'physical.location': 3,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(2)',
         'bind.output': 'gpo(2)',
      },
      'Pin3': {
         'type': 'gpio',
         'physical.location': 4,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(3)',
         'bind.output': 'gpo(3)',
      },
      'Pin4': {
         'type': 'gpio',
         'physical.location': 5,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(4)',
         'bind.output': 'gpo(4)',
      },
      'Pin5': {
         'type': 'gpio',
         'physical.location': 6,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(5)',
         'bind.output': 'gpo(5)',
      },
      'Pin6': {
         'type': 'gpio',
         'physical.location': 7,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(6)',
         'bind.output': 'gpo(6)',
      },
      'Pin7': {
         'type': 'gpio',
         'physical.location': 8,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(7)',
         'bind.output': 'gpo(7)',
      },
      'Pin8': {
         'type': 'gpio',
         'physical.location': 9,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(8)',
         'bind.output': 'gpo(8)',
      },
      'Pin9': {
         'type': 'gpio',
         'physical.location': 10,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(9)',
         'bind.output': 'gpo(9)',
      },
      'Pin10': {
         'type': 'gpio',
         'physical.location': 11,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(10)',
         'bind.output': 'gpo(10)',
      },
      'Pin11': {
         'type': 'gpio',
         'physical.location': 12,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(11)',
         'bind.output': 'gpo(11)',
      },
      'Pin12': {
         'type': 'gpio',
         'physical.location': 13,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(12)',
         'bind.output': 'gpo(12)',
      },
      'Pin13': {
         'type': 'gpio',
         'physical.location': 14,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(13)',
         'bind.output': 'gpo(13)',
      },
      'Pin14': {
         'type': 'gpio',
         'physical.location': 15,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(14)',
         'bind.output': 'gpo(14)',
      },
      'Pin15': {
         'type': 'gpio',
         'physical.location': 22,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(15)',
         'bind.output': 'gpo(15)',
      },
      'Pin16': {
         'type': 'gpio',
         'physical.location': 23,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(16)',
         'bind.output': 'gpo(16)',
      },
      'Pin17': {
         'type': 'gpio',
         'physical.location': 24,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(17)',
         'bind.output': 'gpo(17)',
      },
      'Pin18': {
         'type': 'gpio',
         'physical.location': 25,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(18)',
         'bind.output': 'gpo(18)',
      },
      'Pin19': {
         'type': 'gpio',
         'physical.location': 26,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(19)',
         'bind.output': 'gpo(19)',
      },
      'Pin20': {
         'type': 'gpio',
         'physical.location': 27,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(20)',
         'bind.output': 'gpo(20)',
      },
      'Pin21': {
         'type': 'gpio',
         'physical.location': 28,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(21)',
         'bind.output': 'gpo(21)',
      },
      'Pin22': {
         'type': 'gpio',
         'physical.location': 29,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(22)',
         'bind.output': 'gpo(22)',
      },
      'Pin23': {
         'type': 'gpio',
         'physical.location': 30,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(23)',
         'bind.output': 'gpo(23)',
      },
      'Pin24': {
         'type': 'gpio',
         'physical.location': 31,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(24)',
         'bind.output': 'gpo(24)',
      },
      'Pin25': {
         'type': 'gpio',
         'physical.location': 32,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(25)',
         'bind.output': 'gpo(25)',
      },
      'Pin26': {
         'type': 'gpio',
         'physical.location': 33,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(26)',
         'bind.output': 'gpo(26)',
      },
      'Pin27': {
         'type': 'gpio',
         'physical.location': 34,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(27)',
         'bind.output': 'gpo(27)',
      },
      'Pin28': {
         'type': 'gpio',
         'physical.location': 35,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(28)',
         'bind.output': 'gpo(28)',
      },
      'Pin29': {
         'type': 'gpio',
         'physical.location': 36,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(29)',
         'bind.output': 'gpo(29)',
      },
      'Pin30': {
         'type': 'gpio',
         'physical.location': 37,
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(30)',
         'bind.output': 'gpo(30)',
      },


      'AudioInPinLeft': {
         'type': 'audio.in',
         'physical.location': 16,
         'accept': ['AudioIn'],
         'bind': 'audioin(0)',
      },
      'AudioInPin0': {
         'type': 'audio.in',
         'physical.location': 16,
         'accept': ['AudioIn'],
         'bind': 'audioin(0)',
      },
      'AudioInPinRight': {
         'type': 'audio.in',
         'physical.location': 17,
         'accept': ['AudioIn'],
         'bind': 'audioin(1)',
      },
      'AudioInPin1': {
         'type': 'audio.in',
         'physical.location': 17,
         'accept': ['AudioIn'],
         'bind': 'audioin(1)',
      },
      'AudioOutPinLeft': {
         'type': 'audio.out',
         'physical.location': 18,
         'accept': ['AudioOut'],
         'bind': 'audioout(0)',
      },
      'AudioOutPin0': {
         'type': 'audio.out',
         'physical.location': 18,
         'accept': ['AudioOut'],
         'bind': 'audioout(0)',
      },
      'AudioOutPinRight': {
         'type': 'audio.out',
         'physical.location': 19,
         'accept': ['AudioOut'],
         'bind': 'audioout(1)',
      },
      'AudioOutPin1': {
         'type': 'audio.out',
         'physical.location': 19,
         'accept': ['AudioOut'],
         'bind': 'audioout(1)',
      },

      'AdcPin0': {
         'type': 'adc',
         'physical.location': 22,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(0)',
      },
      'AdcPin1': {
         'type': 'adc',
         'physical.location': 23,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(1)',
      },
      'AdcPin2': {
         'type': 'adc',
         'physical.location': 24,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(2)',
      },
      'AdcPin3': {
         'type': 'adc',
         'physical.location': 25,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(3)',
      },
      'AdcPin4': {
         'type': 'adc',
         'physical.location': 26,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(4)',
      },
      'AdcPin5': {
         'type': 'adc',
         'physical.location': 27,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(5)',
      },
      'AdcPin6': {
         'type': 'adc',
         'physical.location': 28,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(6)',
      },
      'AdcPin7': {
         'type': 'adc',
         'physical.location': 29,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(7)',
      },
      'AdcPin8': {
         'type': 'adc',
         'physical.location': 30,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(8)',
      },
      'AdcPin9': {
         'type': 'adc',
         'physical.location': 31,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(9)',
      },
      'AdcPin10': {
         'type': 'adc',
         'physical.location': 32,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(10)',
      },
      'AdcPin11': {
         'type': 'adc',
         'physical.location': 35,
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(11)',
      },

      'DacPin1': { # not starting at zero because official pin out starts at 1
         'type': 'dac',
         'physical.location': 30,
         'accept': ['CvOut'],
         'bind': 'dac(0)',
      },

      'DacPin2': {
         'type': 'dac',
         'physical.location': 29,
         'accept': ['CvOut'],
         'bind': 'dac(1)',
      },

      # virtual pins for simulator integration tests
      'PinNC': {
         'type': 'gpio',
         'accept': ['Button', 'GateIn', 'GateOut', 'Led', 'LedBi', 'LedRgb', 'Switch'],
         'bind.input': 'gpi(0)',
         'bind.output': 'gpo(0)',
      },
      'AudioInPinNC': {
         'type': 'audio.in',
         'accept': ['AudioIn'],
         'bind': 'audioin(0)',
      },
      'AudioOutPinNC': {
         'type': 'audio.out',
         'accept': ['AudioOut'],
         'bind': 'audioout(0)',
      },
      'AdcPinNC': {
         'type': 'adc',
         'accept': ['CvIn', 'Pot', 'Trim'],
         'bind': 'adc(0)',
      },
      'DacPinNC': {
         'type': 'dac',
         'accept': ['CvOut'],
         'bind': 'dac(0)',
      },
   },
   'kinds': {
      'CvIn': {'pools': ['AdcPin']},
      'CvOut': {'pools': ['DacPin']},
      'GateOut': {'pools': ['GpoPin']},
      'AudioIn': {'pools': ['AudioInPin']},
      'AudioOut': {'pools': ['AudioOutPin']},
      'Led': {'pools': ['GpoPin']},
      'LedBi': {'pools': ['GpoPin', 'GpoPin']},
      'LedRgb': {'pools': ['GpoPin', 'GpoPin', 'GpoPin']},
      'Pot': {'pools': ['AdcPin']},
      'Trim': {'pools': ['AdcPin']},
      'Button': {'pools': ['GpiPin']},
      'GateIn': {'pools': ['GpiPin']},
      'Switch': {'pools': ['GpiPin', 'GpiPin']},
   },
   'pools': {
      'GpiPin': ['Pin0', 'Pin1', 'Pin2', 'Pin3', 'Pin4', 'Pin5', 'Pin6', 'Pin7', 'Pin8', 'Pin9', 'Pin10', 'Pin11'],
      'AdcPin': ['AdcPin0', 'AdcPin1', 'AdcPin2', 'AdcPin3', 'AdcPin4', 'AdcPin5', 'AdcPin6', 'AdcPin9', 'AdcPin10', 'AdcPin11'],
      'GpoPin': ['Pin12', 'Pin13', 'Pin14', 'Pin26', 'Pin27', 'Pin29', 'Pin30'],
      'DacPin': ['DacPin0', 'DacPin1'],
      'AudioInPin': ['AudioInPin0', 'AudioInPin1'],
      'AudioOutPin': ['AudioOutPin0', 'AudioOutPin1'],
   },
}
