##############################################################################
#
#     libdaisy.gyp
#     Copyright (c) 2020 Raphael DINGE
#
#Tab=3########################################################################



{
   'targets' : [
      {
         'target_name': 'libdaisy',
         'type': 'static_library',

         'sources': [
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_adc_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cec.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_comp.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cortex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_crc_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_cryp_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dac_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dcmi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dfsdm.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma2d.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dma_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_dsi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_eth_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_exti.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_fdcan.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_flash_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_gpio.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hash_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hcd.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hrtim.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_hsem.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2c_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_i2s_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_irda.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_iwdg.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_jpeg.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_lptim.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ltdc_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdios.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mdma.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_mmc_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_msp_template.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nand.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_nor.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_opamp_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pcd_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_pwr_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_qspi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_ramecc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rcc_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rng.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_rtc_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sai_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sdram.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sd_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smartcard_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_smbus.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spdifrx.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_spi_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_sram.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_swpmi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_rtc_alarm_template.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_rtc_wakeup_template.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_timebase_tim_template.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_tim_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_uart_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_usart_ex.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_hal_wwdg.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_adc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_bdma.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_comp.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_crc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dac.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_delayblock.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_dma2d.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_exti.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_fmc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_gpio.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_hrtim.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_i2c.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_lptim.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_lpuart.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_mdma.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_opamp.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_pwr.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rcc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rng.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_rtc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_sdmmc.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_spi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_swpmi.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_tim.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usart.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_usb.c',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Src/stm32h7xx_ll_utils.c',

            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_conf_template.c',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_desc_template.c',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c',
            './libDaisy/Middlewares/Third_Party/FatFs/src/diskio.c',
            './libDaisy/Middlewares/Third_Party/FatFs/src/ff.c',
            './libDaisy/Middlewares/Third_Party/FatFs/src/ff_gen_drv.c',
            './libDaisy/Middlewares/Third_Party/FatFs/src/option/ccsbcs.c',

            './libDaisy/core/startup_stm32h750xx.c',

            './libDaisy/src/daisy_core.h',
            './libDaisy/src/daisy_patch.cpp',
            './libDaisy/src/daisy_patch.h',
            './libDaisy/src/daisy_seed.cpp',
            './libDaisy/src/daisy_seed.h',
            './libDaisy/src/daisy.h',

            './libDaisy/src/dev/codec_ak4556.cpp',
            './libDaisy/src/dev/codec_ak4556.h',
            './libDaisy/src/dev/flash_IS25LP064A.h',
            './libDaisy/src/dev/flash_IS25LP080D.h',
            './libDaisy/src/dev/leddriver.h',
            './libDaisy/src/dev/sdram.c',
            './libDaisy/src/dev/sdram.h',
            './libDaisy/src/dev/sr_595.cpp',
            './libDaisy/src/dev/sr_595.h',
            './libDaisy/src/dev/sr_4021.h',

            './libDaisy/src/hid/audio.cpp',
            './libDaisy/src/hid/audio.h',
            './libDaisy/src/hid/ctrl.cpp',
            './libDaisy/src/hid/ctrl.h',
            './libDaisy/src/hid/encoder.cpp',
            './libDaisy/src/hid/encoder.h',
            './libDaisy/src/hid/gatein.cpp',
            './libDaisy/src/hid/gatein.h',
            './libDaisy/src/hid/led.cpp',
            './libDaisy/src/hid/led.h',
            './libDaisy/src/hid/logger.cpp',
            './libDaisy/src/hid/logger.h',
            './libDaisy/src/hid/midi.cpp',
            './libDaisy/src/hid/midi.h',
            './libDaisy/src/hid/oled_display.cpp',
            './libDaisy/src/hid/oled_display.h',
            './libDaisy/src/hid/parameter.cpp',
            './libDaisy/src/hid/parameter.h',
            './libDaisy/src/hid/rgb_led.cpp',
            './libDaisy/src/hid/rgb_led.h',
            './libDaisy/src/hid/switch.cpp',
            './libDaisy/src/hid/switch.h',
            './libDaisy/src/hid/usb.cpp',
            './libDaisy/src/hid/usb.h',
            './libDaisy/src/hid/wavplayer.cpp',
            './libDaisy/src/hid/wavplayer.h',

            './libDaisy/src/per/adc.cpp',
            './libDaisy/src/per/adc.h',
            './libDaisy/src/per/dac.c',
            './libDaisy/src/per/dac.h',
            './libDaisy/src/per/gpio.c',
            './libDaisy/src/per/gpio.h',
            './libDaisy/src/per/i2c.cpp',
            './libDaisy/src/per/i2c.h',
            './libDaisy/src/per/qspi.c',
            './libDaisy/src/per/qspi.h',
            './libDaisy/src/per/sai.cpp',
            './libDaisy/src/per/sai.h',
            './libDaisy/src/per/sdmmc.cpp',
            './libDaisy/src/per/sdmmc.h',
            './libDaisy/src/per/spi.cpp',
            './libDaisy/src/per/spi.h',
            './libDaisy/src/per/tim.cpp',
            './libDaisy/src/per/tim.h',
            './libDaisy/src/per/uart.cpp',
            './libDaisy/src/per/uart.h',

            './libDaisy/src/sys/dma.c',
            './libDaisy/src/sys/dma.h',
            './libDaisy/src/sys/fatfs.c',
            './libDaisy/src/sys/fatfs.h',
            './libDaisy/src/sys/ffconf.h',
            './libDaisy/src/sys/stm32h7xx_hal_conf.h',
            './libDaisy/src/sys/system_stm32h7xx.c',
            './libDaisy/src/sys/system.cpp',
            './libDaisy/src/sys/system.h',

            './libDaisy/src/usbd/usbd_cdc_if.c',
            './libDaisy/src/usbd/usbd_cdc_if.h',
            './libDaisy/src/usbd/usbd_conf.c',
            './libDaisy/src/usbd/usbd_conf.h',
            './libDaisy/src/usbd/usbd_desc.c',
            './libDaisy/src/usbd/usbd_desc.h',

            './libDaisy/src/util/bsp_sd_diskio.c',
            './libDaisy/src/util/bsp_sd_diskio.h',
            './libDaisy/src/util/color.cpp',
            './libDaisy/src/util/color.h',
            './libDaisy/src/util/hal_map.c',
            './libDaisy/src/util/hal_map.h',
            './libDaisy/src/util/oled_fonts.c',
            './libDaisy/src/util/oled_fonts.h',
            './libDaisy/src/util/ringbuffer.h',
            './libDaisy/src/util/scopedirqblocker.h',
            './libDaisy/src/util/sd_diskio.c',
            './libDaisy/src/util/sd_diskio.h',
            './libDaisy/src/util/unique_id.c',
            './libDaisy/src/util/unique_id.h',
            './libDaisy/src/util/wav_format.h',
         ],

         'include_dirs': [
            './libDaisy/src',
            './libDaisy/src/sys',
            './libDaisy/src/usbd',
            './libDaisy/Drivers/CMSIS/Include',
            './libDaisy/Drivers/CMSIS/Device/ST/STM32H7xx/Include',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Inc',
            './libDaisy/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Inc',
            './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc',
            './libDaisy/Middlewares/Third_Party/FatFs/src',
         ],

         'cflags': [
            '-Wno-missing-attributes',
            '-Wno-unused-parameter',
            '-Wno-strict-aliasing',
            '-Wno-maybe-uninitialized',
            '-Wno-attributes',
            '-Wno-missing-field-initializers',
            '-Wno-ignored-qualifiers',
            '-Wno-unused-function',
         ],

         'cflags!': [
            '-Wpedantic',
         ],

         'cflags_c': [
            '-Wno-old-style-declaration',
         ],

         'direct_dependent_settings': {
            'include_dirs': [
               './libDaisy/src',
               './libDaisy/src/sys',
               './libDaisy/src/usbd',
               './libDaisy/Drivers/CMSIS/Include',
               './libDaisy/Drivers/CMSIS/Device/ST/STM32H7xx/Include',
               './libDaisy/Drivers/STM32H7xx_HAL_Driver/Inc',
               './libDaisy/Drivers/STM32H7xx_HAL_Driver/Inc/Legacy',
               './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Core/Inc',
               './libDaisy/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc',
               './libDaisy/Middlewares/Third_Party/FatFs/src',
            ],
         },
      },
   ],
}
